# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2890325f37350bfb37dd89e124f9344f086fc8ab84ebee66453877e791ee851244ab216d56360a0788883369f564355a7776ac8003d4ab5a38279b8b801933f

test:
  secret_key_base: 686592e2b3b2fa99b8517e6198c58d2f3395753b6b8032885c7c3cd80f4fa8366949d8fd52dc062410d8c36943bb006b1c6668e7648744c6093fab8f2874e3d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
